import type { Tenant } from "@/src/domain/site";

const ivyStationCalendarSrc = [
  "https://calendar.google.com/calendar/embed?height=600",
  "&wkst=1",
  "&bgcolor=%23ffffff",
  "&ctz=America/Los_Angeles",
  "&showTitle=0",
  "&showPrint=0",
  "&showTabs=0",
  "&showCalendars=0",
  "&showTz=0",
  "&mode=AGENDA",
  "&src=Y185OThnMTJnNzNmZmNwMHJiN2s0OXRrbHQyb0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t",
  "&src=bmZsXzI0XyU0Y29zKyU0MW5nZWxlcyslNDNoYXJnZXJzI3Nwb3J0c0Bncm91cC52LmNhbGVuZGFyLmdvb2dsZS5jb20",
  "&src=Z2ZoNnRxdGczZGFsOTMzNjIycmRwdnFzNzBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ",
  "&src=N2x2dXFlbjFkazA5ajI2cXNiMW03ajVsNGNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ",
  "&src=bmhsXzhfJTRjb3MrJTQxbmdlbGVzKyU0YmluZ3Mjc3BvcnRzQGdyb3VwLnYuY2FsZW5kYXIuZ29vZ2xlLmNvbQ",
  "&src=bmZsXzE0XyU0Y29zKyU0MW5nZWxlcyslNTJhbXMjc3BvcnRzQGdyb3VwLnYuY2FsZW5kYXIuZ29vZ2xlLmNvbQ",
  "&src=bmNhYWZfNjRfJTU1JTQzJTRjJTQxKyU0MnJ1aW5zI3Nwb3J0c0Bncm91cC52LmNhbGVuZGFyLmdvb2dsZS5jb20",
  "&src=bmNhYWZfNjJfJTU1JTUzJTQzKyU1NHJvamFucyNzcG9ydHNAZ3JvdXAudi5jYWxlbmRhci5nb29nbGUuY29t",
].join("");

const hawthorneCalendarSrc = [
  "https://calendar.google.com/calendar/embed?height=600",
  "&wkst=1",
  "&bgcolor=%23ffffff",
  "&ctz=America/Los_Angeles",
  "&showTitle=0",
  "&showNav=1",
  "&showPrint=0",
  "&showCalendars=0",
  "&showTz=0",
  "&mode=AGENDA",
  "&src=aDQ1bGI1MmsycTk4ZjZsN2lwNzc3ZjFhZ2dAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ",
  "&src=bmZsXzI0XyU0Y29zKyU0MW5nZWxlcyslNDNoYXJnZXJzI3Nwb3J0c0Bncm91cC52LmNhbGVuZGFyLmdvb2dsZS5jb20",
  "&src=Z2ZoNnRxdGczZGFsOTMzNjIycmRwdnFzNzBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ",
  "&src=N2x2dXFlbjFkazA5ajI2cXNiMW03ajVsNGNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ",
  "&src=bmZsXzE0XyU0Y29zKyU0MW5nZWxlcyslNTJhbXMjc3BvcnRzQGdyb3VwLnYuY2FsZW5kYXIuZ29vZ2xlLmNvbQ",
  "&src=bmNhYWZfNjRfJTU1JTQzJTRjJTQxKyU0MnJ1aW5zI3Nwb3J0c0Bncm91cC52LmNhbGVuZGFyLmdvb2dsZS5jb20",
  "&src=bmNhYWZfNjJfJTU1JTUzJTQzKyU1NHJvamFucyNzcG9ydHNAZ3JvdXAudi5jYWxlbmRhci5nb29nbGUuY29t",
  "&src=ZW4udXNhI2hvbGlkYXlAZ3JvdXAudi5jYWxlbmRhci5nb29nbGUuY29t",
  "&color=%23D81B60",
  "&color=%23F4511E",
  "&color=%23616161",
  "&color=%23E67C73",
  "&color=%23B39DDB",
  "&color=%23B39DDB",
  "&color=%23B39DDB",
  "&color=%230B8043",
].join("");

export const laawLifeTenant = {
  id: "laaw-life",
  slug: "laaw-life",
  displayName: "LAAW Life",
  defaultLocationId: "ivy-station",
  locations: [
    {
      id: "ivy-station",
      slug: "ivy",
      displayName: "Ivy Station",
      calendarHeading: "Ivy Station",
      calendar: {
        provider: "google-calendar-embed",
        src: ivyStationCalendarSrc,
      },
    },
    {
      id: "hawthorne",
      slug: "hawthorne",
      displayName: "Hawthorne",
      calendarHeading: "Hawthorne",
      calendar: {
        provider: "google-calendar-embed",
        src: hawthorneCalendarSrc,
      },
    },
  ],
} as const satisfies Tenant;
